<buttom class="btn btn-success" onclick="location.href='/admin/sexos/save'">Novo Sexo</buttom>

<table class="table">
	<thead>
	<tr>
		<td>Id</td><td>Descrição</td>
	</tr>
	</thead>
	<tbody>
		<?php foreach($sexos as $sexo){
		?>
			<tr>
				<td>
					<?php echo $sexo->getId(); ?>
				</td>
				<td>
					<?php echo $sexo->getDescSexo(); ?>
				</td>
				<td>
					<a href="/admin/sexos/save/id/ <?php echo $sexo->getId(); ?>">Editar</a>
				</td>
				<td>
					<a href="/admin/sexos/delete/id/ <?php echo $sexo->getId(); ?>">Excluir</a>
				</td>
			</tr>
			<?php } ?>
		</tbody>
		
