<buttom class="btn btn-success" onclick="location.href = '/admin/filiacoes/save'">Novo Filiacao</buttom>

<table class="table">
    <thead>
        <tr>
            <td>Id</td><td>Pai</td><td>Mãe</td>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($filiacoes as $filiacao) {
            ?>
            <tr>
                <td>
                    <?php echo $filiacao->getId(); ?>
                </td>
                <td>
                    <?php echo $filiacao->getDescPai(); ?>
                </td>
                <td>
                    <?php echo $filiacao->getDescMae(); ?>
                </td>
                <td>
                    <a href="/admin/filiacoes/save/id/ <?php echo $filiacao->getId(); ?>">Editar</a>
                </td>
                <td>
                    <a href="/admin/filiacoes/delete/id/ <?php echo $filiacao->getId(); ?>">Excluir</a>
                </td>
            </tr>

        <?php } ?>
    </tbody>
    
    <?php
    echo $this->paginationCOntrol(
            $interesses, 'sliding', 'admin/partials/paginator/paginator.phtml', array(
        'route' => 'filiacoes',
            )
    );
    ?>



