<buttom class="btn btn-success" onclick="location.href='/admin/telefones/save'">Novo Telefone</buttom>

<table class="table">
	<thead>
	<tr>
		<td>Id</td><td>Descrição</td>
	</tr>
	</thead>
	<tbody>
		<?php foreach($telefones as $telefone){
		?>
			<tr>
				<td>
					<?php echo $telefone->getId(); ?>
				</td>
				<td>
					<?php echo $telefone->getDescTelefone(); ?>
				</td>
				<td>
					<a href="/admin/telefones/save/id/ <?php echo $telefone->getId(); ?>">Editar</a>
				</td>
				<td>
					<a href="/admin/telefones/delete/id/ <?php echo $telefone->getId(); ?>">Excluir</a>
				</td>
			</tr>
			<?php } ?>
		</tbody>
		
