<form action="/admin/login/login" method="post">
    <div>
        <label>Posts</label>
    </div>
        <?php 
         var_dump('ageitar no index para exibir o titulo e o post . o Valor que ta buscando dos posts é:'.$post);                
            foreach($post as $key => $posts){
               
            }
        ?>
    <div>
        <input type="password" name="senha">
    </div>
    <div class="actions">
        <input type="submit" value="Entrar">
    </div>
</form>